languages: python
python:
        - 3.6
        - 3.7
before_install:
        - pip3 install coverage==3.7.1 codecov
        - pip3 intall tox-travis
        - pip3 install -r requirements.txt
scripts:
        - tox
